name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install prettier plugins
        run: |
          npm install prettier-plugin-multiline-arrays
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --config .prettierrc --check ./**/*.ts
          prettier_plugins: 'prettier-plugin-multiline-arrays'
